[package]
name = "sstable"
version = "0.1.0"
edition = "2024"

[dependencies]
integer-encoding = "4.0.2"
key_value = {path = "../key_value"}
thiserror = "2.0.12"
tempfile = "3.19.1"
log = "0.4.27"
env_logger = "0.11.7"
bloomfilter = "3"
