[package]
name = "sstable"
version = "0.1.0"
edition = "2024"

[dependencies]
integer-encoding = "4.0.2"
bloomfilter = "3"
key_value = {path = "../key_value"}
thiserror = "2.0.12"
tempfile = "3.19.1"

